workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        UNITY_VERSION: 2022.3.10f1
        XCODE_PROJECT_PATH: "ios"
      ios_signing:
        distribution_type: app_store
        # ВАЖНО: Впишите сюда ваш реальный ID (например com.avrgroup.astra)
        bundle_identifier: com.ваш.реальный.id
    scripts:
      - name: Activate Unity License
        script: | 
          # Создаем файл лицензии из переменной (для Personal версии)
          echo "$UNITY_LICENSE" > "Unity_v5.x.ulf"
          
          # Активируем лицензию
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -manualLicenseFile Unity_v5.x.ulf || exit 0
      
      - name: Build Unity to Xcode
        script: | 
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -projectPath . \
            -executeMethod BuildScript.BuildIOS \
            -nographics
            
      - name: Build IPA from Xcode
        script: | 
          xcode-project build-ipa \
            --project "$XCODE_PROJECT_PATH/Unity-iPhone.xcodeproj" \
            --scheme "Unity-iPhone"

    artifacts:
      - build/ios/*.ipa
      - $XCODE_PROJECT_PATH/*.ipa

    publishing:
      app_store_connect:
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        private_key: $APP_STORE_PRIVATE_KEY
        submit_to_testflight: true