workflows:
  unity-ios-build:
    name: Unity iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    # Подключаем App Store Connect интеграцию
    integrations:
      app_store_connect: ios_credentials

    environment:
      # Подключаем группу переменных (ключи, сертификаты и т.п.)
      groups:
        - ios_credentials
      ios_signing:
        distribution_type: app_store
        # Этот идентификатор должен быть такими же в Unity/Apple
        bundle_identifier: "Comeback.uz.Lemala.ComeBack"

      vars:
        # Путь к Unity iOS выходной папке
        UNITY_IOS_DIR: ios
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        APP_STORE_APPLE_ID: 1570610860

    scripts:
      - name: Activate Unity license
        script: |
          # activate Unity (Serial+Email+Password из переменных)
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -serial ${UNITY_SERIAL} -username ${UNITY_EMAIL} -password ${UNITY_PASSWORD}

      - name: Generate Xcode project
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile \
            -projectPath . -executeMethod BuildScript.BuildIos -nographics

      - name: Set up keychain for codesigning
        script: |
          keychain initialize

      - name: Fetch signing certificates & profiles
        script: |
          # Добавляем флаг --create для автоматической генерации профиля
          app-store-connect fetch-signing-files "ios" --type IOS_APP_STORE --create --allow-managed

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Configure signing profiles
        script: |
          cd $UNITY_IOS_DIR
          xcode-project use-profiles

      - name: Set build number
        script: |
          BUILD_NUMBER=$(($(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID") + 1))
          cd $UNITY_IOS_DIR
          agvtool new-version -all $BUILD_NUMBER

      - name: Build .ipa
        script: |
          cd $UNITY_IOS_DIR
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        # Указываем переменные, которые вы создали в Codemagic UI
        auth: key_id
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        private_key: $APP_STORE_CONNECT_PRIVATE_KEY
        submit_to_testflight: true

      email:
        recipients:
          - youremail@example.com
        notify:
          success: true
          failure: true