workflows:
  unity-ios-build:
    name: Unity iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    # Интеграция не используется — credentials через переменные в группе ios
    environment:
      groups:
        - ios # CERTIFICATE_PRIVATE_KEY, APP_STORE_CONNECT_*, etc.
        - unity_credentials # UNITY_SERIAL, UNITY_EMAIL, UNITY_PASSWORD
      
      # Устанавливает Unity 6000.3.7f1 и задаёт UNITY_HOME
      unity: 6000.3.7f1

      vars:
        BUNDLE_ID: "Comeback.uz.Lemala.ComeBack"
        UNITY_IOS_DIR: "ios"
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_WORKSPACE: "Unity-iPhone.xcworkspace"
        XCODE_SCHEME: "Unity-iPhone"
        APP_STORE_APPLE_ID: 6751400452 # ID из App Store Connect

    scripts:
      - name: Activate Unity license
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -serial ${UNITY_SERIAL} -username ${UNITY_EMAIL} -password ${UNITY_PASSWORD}

      - name: Generate Xcode project
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -projectPath . -executeMethod BuildScript.BuildIOS -nographics

      - name: Set up keychain for codesigning
        script: |
          keychain initialize

      - name: Fetch signing certificates & profiles
        script: |
          # Требуется CERTIFICATE_PRIVATE_KEY в группе ios (приватный ключ RSA)
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Configure signing profiles
        script: |
          cd $UNITY_IOS_DIR
          xcode-project use-profiles --project "$XCODE_PROJECT" --archive-method app-store

      - name: Install CocoaPods dependencies
        script: |
          cd $UNITY_IOS_DIR
          pod install

      - name: Set build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          cd $UNITY_IOS_DIR
          agvtool new-version -all $BUILD_NUMBER

      - name: Build .ipa
        script: |
          cd $UNITY_IOS_DIR
          xcode-project build-ipa --workspace "$XCODE_WORKSPACE" --scheme "$XCODE_SCHEME"

    artifacts:
      - ios/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      scripts:
        - name: Deactivate Unity license
          script: |
            $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - -returnlicense \
              -username ${UNITY_EMAIL} -password ${UNITY_PASSWORD}
          ignore_failure: true

      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: true

      email:
        recipients:
          - youremail@example.com
        notify:
          success: true
          failure: true