workflows:
  unity-ios-build:
    name: Unity iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2

    integrations:
      app_store_connect: ios_credentials

    environment:
      groups:
        - ios # Имя группы из ваших настроек
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: "Comeback.uz.Lemala.ComeBack" # Исправленный ID

      vars:
        UNITY_IOS_DIR: "ios"
        XCODE_PROJECT: "Unity-iPhone.xcodeproj"
        XCODE_SCHEME: "Unity-iPhone"
        APP_STORE_APPLE_ID: 6751400452 # ID из App Store Connect

    scripts:
      - name: Activate Unity license
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -serial ${UNITY_SERIAL} -username ${UNITY_EMAIL} -password ${UNITY_PASSWORD}

      - name: Generate Xcode project
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -logFile - \
            -projectPath . -executeMethod BuildScript.BuildIos -nographics

      - name: Set up keychain for codesigning
        script: |
          keychain initialize

      - name: Fetch signing certificates & profiles
        script: |
          app-store-connect fetch-signing-files "Comeback.uz.Lemala.ComeBack" --type IOS_APP_STORE --create

      - name: Add certificates to keychain
        script: |
          keychain add-certificates

      - name: Configure signing profiles
        script: |
          cd $UNITY_IOS_DIR
          xcode-project use-profiles

      - name: Set build number
        script: |
          LATEST_BUILD=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          BUILD_NUMBER=$((LATEST_BUILD + 1))
          cd $UNITY_IOS_DIR
          agvtool new-version -all $BUILD_NUMBER

      - name: Build .ipa
        script: |
          cd $UNITY_IOS_DIR
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"

      - name: Deactivate Unity license
        script: |
          $UNITY_HOME/Contents/MacOS/Unity -batchmode -quit -returnlicense -logFile -
        ignore_failure: true # Чтобы билд не падал, если лицензия уже деактивирована

    artifacts:
      - ios/build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM

    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true

      email:
        recipients:
          - youremail@example.com
        notify:
          success: true
          failure: true